bundleserver/README.md
Formatting and M2 applicable changes
=> Updates server README.md

bundleserver/pom.xml, bundleserver/src/main/java/com/ddd/server/BundleServerApplication.java, bundleserver/src/main/java/com/ddd/server/commands/CLRunner.java, bundleserver/src/main/java/com/ddd/server/commands/CommandProcessor.java, bundleserver/src/main/java/com/ddd/server/commands/bundleuploader/BundleUploader.java
add more general processing of CLI commands and initial validation of config
=> Command support and config validation

BundleClient/app/build.gradle, BundleTransport/app/build.gradle
OS arch-based GRPC artifact configuration to avoid manual editing of gradle build script for Mac M1 and M2
=> OS arch based grpc artifact configuration

bundleserver/pom.xml, bundleserver/src/main/java/com/ddd/server/BundleServerApplication.java
=> Figlet banner for Bundle Server

.github/workflows/actions.yml, BundleClient/app/src/main/java/com/ddd/client/bundlesecurity/ClientSecurity.java, bundleserver/src/main/java/com/ddd/server/bundlerouting/ServerWindow.java
Using a Personal Access Token to trigger workflow checks after github-actions[bot] commits code.
=> Workflow update

apps/echo/server/pom.xml, apps/echo/server/src/main/java/net/discdd/app/echo/EchoApplication.java, apps/echo/server/src/main/java/net/discdd/app/echo/EchoDDDAdapter.java, apps/echo/server/src/main/resources/application.properties, apps/echo/server/src/test/java/net/discdd/app/echo/EchoApplicationTests.java, serviceadapter-core/README, serviceadapter-core/pom.xml, serviceadapter-core/src/main/proto/ServiceAdapter.proto, serviceadapter-core/src/main/proto/ServiceAdapterRegistry.proto
The initial checkin for BundleServer <-> ServiceAdapter core library.
It includes the echo test ServiceAdapter.
The next change will make BundleServer use this library.
=> refactored BundleServer -> ServiceAdapter core library

BundleTransport/app/src/main/java/com/ddd/bundletransport/MainActivity.java, BundleTransport/app/src/main/java/com/ddd/wifidirect/WifiDirectBroadcastReceiver.java, BundleTransport/app/src/main/java/com/ddd/wifidirect/WifiDirectManager.java, BundleTransport/app/src/main/java/com/ddd/wifidirect/WifiDirectStateListener.java, BundleTransport/app/src/main/res/layout/activity_main.xml
Display connected and nearby devices in Transport App
=> Display connected and nearby devices in Transport App

.gitignore, BundleClient/app/src/main/java/com/ddd/client/bundlesecurity/BundleSecurity.java, BundleClient/app/src/main/java/com/ddd/utils/ADUUtils.java, bundleserver/src/main/java/com/ddd/server/bundlesecurity/BundleSecurity.java, bundleserver/src/main/java/com/ddd/server/bundletransmission/BundleTransmission.java, bundleserver/src/main/java/com/ddd/server/config/BundleServerConfig.java, bundleserver/src/main/java/com/ddd/utils/ADUUtils.java
Used IntelliJ Inspect Code feature and removed unused imports and functions
=> Mini Code cleanup

pom.xml, settings.gradle
this allows us to checkout DDD as a maven project and get all the other maven DDD projects as subprojects.
=> create a top-level maven pom.xml for DDD

BundleClient/app/src/main/AndroidManifest.xml
Make the path changes to MessageProvider and HelloworldActivity from com.ddd to net.discdd
=> Make the path changes to MessageProvider and HelloworldActivity

BundleClient/app/src/main/java/net/discdd/datastore/providers/MessageProvider.java
Added selection argument to the Provider to query the bundleClientId
=> Added selection argument to the Provider to query the bundleClientId

BundleClient/app/src/main/java/net/discdd/bundleclient/HelloworldActivity.java
external storage permission remove after android 10
=> removed check for write external storage permission

bundleserver/src/main/java/net/discdd/server/applicationdatamanager/AduStores.java
=> Removed unintended changes

BundleClient/app/src/main/java/net/discdd/datastore/providers/MessageProvider.java, BundleClient/build.gradle, apps/k9/server/src/main/java/net/discdd/app/k9/K9DDDAdapter.java, apps/k9/server/src/main/java/net/discdd/app/k9/utils/MailUtils.java, apps/k9/server/src/main/resources/application.properties, bundle-core/src/main/java/net/discdd/utils/StoreADUs.java
Adapter changes fixing comments from the previous PR.
StoreADU Util methods for message provider.
=> K9 Adapter and BundleCore Updates

bundle-core/src/main/java/net/discdd/utils/StoreADUs.java, bundleserver/src/main/java/net/discdd/server/BundleServerApplication.java, bundleserver/src/main/java/net/discdd/server/config/ServerSecurityConfig.java, bundleserver/src/main/java/net/discdd/server/repository/ServerRoutingId.java, bundleserver/src/main/resources/application.yml
Set the Log level to WARN if doing a CLI
Removed timestamps from logging if doing a CLI
Cleaned up some of the warnings
Don't try to be a gRPC server if doing a CLI
=> Cleaned up BundleServer CLI

BundleClient/app/src/main/java/net/discdd/bundleclient/GrpcReceiveTask.java, BundleClient/app/src/main/java/net/discdd/client/bundletransmission/BundleTransmission.java, BundleTransport/app/src/main/java/net/discdd/bundletransport/RpcServer.java, bundle-core/src/main/java/net/discdd/bundlerouting/BundleSender.java, bundle-core/src/main/java/net/discdd/bundlerouting/GrpcReceiveTask.java, bundle-core/src/main/java/net/discdd/bundlerouting/GrpcSendTask.java, bundle-core/src/main/java/net/discdd/bundlerouting/service/FileServiceImpl.java, bundle-core/src/main/java/net/discdd/utils/FileUtils.java, bundle-core/src/main/proto/BundleService.proto, bundle-core/src/main/proto/FileService.proto, bundleserver/src/main/java/net/discdd/server/bundletransmission/BundleTransmission.java, bundleserver/src/main/java/net/discdd/server/commands/bundleuploader/BundleUploader.java, bundleserver/src/main/java/net/discdd/server/service/BundleServerServiceImpl.java, bundleserver/src/main/java/net/discdd/server/service/ClientFileServiceImpl.java, bundleserver/src/test/java/net/discdd/server/ADUEnd2EndTest.java
Making Sender a struct with a name and a type keeps key information about the name together.
=> make BundleSender a struct in the FileService.proto

bundleserver/src/main/java/net/discdd/server/bundlerouting/ServerWindowService.java, bundleserver/src/main/java/net/discdd/server/bundlesecurity/BundleSecurity.java, bundleserver/src/main/java/net/discdd/server/bundletransmission/BundleTransmission.java, bundleserver/src/main/java/net/discdd/server/repository/entity/ServerWindow.java
updated serverwindow logic -> update current counter after every new bundle generated
=> adjusted serverwindow repo

bundle-core/src/main/java/net/discdd/bundlesecurity/BundleIDGenerator.java
the current counters stop working after 255 messages... this fixes it but breaks everything. all clients, transports, and servers need to be updated.
=> make bundle counter a long rather than a byte

BundleClient/app/src/main/java/net/discdd/bundleclient/BundleClientWifiDirectService.java, BundleClient/app/src/main/java/net/discdd/datastore/providers/MessageProvider.java, mysignal/app/build.gradle, mysignal/app/src/main/AndroidManifest.xml, mysignal/app/src/main/java/com/example/mysignal/MainActivity.java, mysignal/app/src/main/java/com/example/mysignal/ReceiveIntentService.java, mysignal/app/src/main/res/layout/activity_main.xml
changed broadcast to data received notification instead remodified mysignal for better testing experiment
=> app get received adus from client

BundleTransport/app/src/main/java/net/discdd/bundletransport/ServerUploadFragment.java, BundleTransport/app/src/main/java/net/discdd/bundletransport/TransportToBundleServerManager.java, bundle-core/src/main/java/net/discdd/bundlesecurity/SecurityUtils.java, bundle-core/src/main/java/net/discdd/transport/TransportSecurity.java
allow stable gRPC call with bundle-server
=> temporary use static transport id instead of transportSecurity transportId

bundle-core/src/main/java/net/discdd/client/applicationdatamanager/ApplicationDataManager.java, bundle-core/src/main/java/net/discdd/client/bundlerouting/ClientBundleGenerator.java, bundle-core/src/main/java/net/discdd/client/bundlerouting/ClientRouting.java, bundle-core/src/main/java/net/discdd/client/bundlerouting/ClientWindow.java, bundle-core/src/main/java/net/discdd/client/bundlesecurity/BundleSecurity.java, bundle-core/src/main/java/net/discdd/client/bundlesecurity/ClientSecurity.java, bundle-core/src/main/java/net/discdd/client/bundletransmission/BundleTransmission.java, bundle-core/src/main/java/net/discdd/pathutils/ClientPaths.java, bundle-core/src/main/java/net/discdd/pathutils/TransportPaths.java, bundleserver/src/test/java/net/discdd/server/BundleClientToBundleServerTest.java
fixed small method mistake in transportPaths
=> refined paths in client with clientPaths class

bundleserver/pom.xml, bundleserver/src/main/java/net/discdd/server/bundlesecurity/BundleSecurity.java, bundleserver/src/main/java/net/discdd/server/bundletransmission/BundleTransmission.java
we had a dependabot alert on commons.io, but we only used it in one location, so i just changed the code to remove the dependency.
=> remove dependency on commons.io

BundleClient/app/src/main/java/net/discdd/bundleclient/BundleClientActivity.java, BundleTransport/app/src/main/java/net/discdd/bundletransport/BundleTransportActivity.java, android-core/src/main/java/net/discdd/android/fragments/PermissionsFragment.java, android-core/src/main/java/net/discdd/android/fragments/PermissionsViewModel.java
- made changes to both bundle client & transport
- view model class to manage state of permissions being satisfied or not
- tab bar will now only show tabs if all permissions are satisfied
=> only show enabled tabs in client apps

BundleTransport/app/src/main/java/net/discdd/bundletransport/BundleTransportActivity.java, BundleTransport/app/src/main/java/net/discdd/bundletransport/UsbFileManager.java, BundleTransport/app/src/main/java/net/discdd/bundletransport/UsbFragment.java
allows usb tab to render if and only if usb is attached and other permissions are met.
allows all other tabs to render if permissions are met.
=> Usb tab visibility

android-core/src/main/java/net/discdd/crashreports/AcraApp.java, android-core/src/main/java/net/discdd/crashreports/LocalReportSender.java
Adds a method that allows us to gather more reports but not too many.
=> Adds optimizeReports method

BundleClient/app/src/main/java/net/discdd/bundleclient/BundleClientActivity.java, BundleClient/app/src/main/java/net/discdd/bundleclient/UsbFragment.java
Functions properly working now, fixed the initial bug of the usb not connecting at app start. Removed redundant methods for usb that were not needed anymore.
=> Fixed  initial bug of the usb app not connecting and removed redundant code

BundleTransport/app/src/main/java/net/discdd/bundletransport/BundleTransportActivity.java, BundleTransport/app/src/main/java/net/discdd/bundletransport/UsbFragment.java
BundleTransport now successfully removes/adds the usbfragment when usb unplugged/plugged and updates the usbstatus depending on if directory was found, usb bug fixed, it works if plugged in before app initialization
=> BundleTransport USB fixes

BundleClient/app/src/main/res/layout/usb_fragment.xml, BundleClient/app/src/main/res/values-b+ar/strings.xml, BundleClient/app/src/main/res/values-b+es/strings.xml, BundleClient/app/src/main/res/values-b+uk/strings.xml, BundleClient/app/src/main/res/values/strings.xml, BundleTransport/app/src/main/res/values-b+ar/strings.xml, BundleTransport/app/src/main/res/values-b+es/strings.xml, BundleTransport/app/src/main/res/values-b+uk/strings.xml, BundleTransport/app/src/main/res/values/strings.xml
Added string translations for BundleClient and BundleTransport
=> String translations

bundleserver/src/main/java/net/discdd/server/BundleServerApplication.java, bundleserver/src/main/resources/application.yml
=> use system set properties for custom properties

BundleTransport/app/src/main/java/net/discdd/bundletransport/viewmodels/StorageViewModel.kt
The savePreference and retrievePreference methods had non matching datatypes. So I updated the retrievePreference method.
Closes #529
=> fix StorageViewModel instantiation error

.github/workflows/release.yml, BundleClient/app/build.gradle, BundleClient/app/src/main/java/net/discdd/bundleclient/screens/BundleManagerScreen.kt, BundleClient/app/src/main/res/values/strings.xml, BundleTransport/app/build.gradle, build.gradle
the build actually happens on the SJSU-office machine, but everything is built from the docker image with
secrets in GitHub so that they are reproducible.
=> build play store artifacts in github

BundleClient/app/src/main/java/net/discdd/bundleclient/BundleClientActivity.kt, BundleClient/app/src/main/java/net/discdd/bundleclient/BundleClientWifiDirectService.java, build.gradle
hot fix for rogue wifiaware code
=> Prepare for alpha 3 on play store

BundleClient/app/src/main/res/values/strings.xml
BundleClient doesn't mean anything to the user.
DDD Client may not be much better, but we do have the common DDD in DDD mail, DDD client, DDD transport
=> change BundleClient to DDD Client

bundle-core/src/main/java/net/discdd/client/bundletransmission/BundleTransmission.java
improves error handling when the client probes for bundles.
=> client BundleTransmission download error handling

apps/k9/server/src/main/java/net/discdd/app/k9/model/RegisterAdu.java
we changed the RegisterAdu to only require a single prefix and suffix
=> fix RegisterAdu to handle since fixes

apps/k9/server/src/main/java/net/discdd/app/k9/K9DDDAdapter.java, apps/k9/server/src/main/java/net/discdd/app/k9/repository/entity/K9ClientIdToEmailMapping.java, apps/k9/server/src/main/java/net/discdd/app/k9/utils/MailUtils.java
if there are too many recipients (more than 5) or an invalid destination or not ravlykmail.com send a bounce message back to sender.
=> K9 bounce mail

apps/k9/server/pom.xml, apps/k9/server/src/main/java/net/discdd/app/k9/K9DDDAdapter.java, apps/k9/server/src/main/java/net/discdd/app/k9/service/EmailService.java, apps/k9/server/src/main/java/net/discdd/app/k9/utils/MailUtils.java
adds the following properties to use an SMTP relay:
smtp.relay.host
smtp.relay.port
smtp.localDomain
=> enable sending emails to external addresses

apps/k9/server/pom.xml, apps/k9/server/src/main/java/net/discdd/app/k9/K9Config.java, apps/k9/server/src/main/java/net/discdd/app/k9/K9DDDAdapter.java, apps/k9/server/src/main/java/net/discdd/app/k9/repository/entity/K9ClientIdToEmailMapping.java, apps/k9/server/src/main/java/net/discdd/app/k9/service/EmailService.java
also added support for DKIM on outgoing mail
=> add support for SMTP incoming mail

BundleClient/app/build.gradle, BundleClient/app/src/main/java/net/discdd/bundleclient/BundleClientActivity.kt, bundle-core/src/main/java/net/discdd/utils/StoreADUs.java
- turned on leaked open file stacktraces for debug
- cleaned up existing leaks
=> leaked closes cleanup

apps/k9/common/src/main/java/net/discdd/app/k9/common/ControlAdu.java, apps/k9/common/src/test/java/net/discdd/app/k9/common/ControlAduTest.java, apps/k9/server/src/main/java/net/discdd/app/k9/K9DDDAdapter.java
login passes the email address to login, so we should call the parameter email() instead of username()
=> change the email parameter of LoginControlAdu

apps/k9/server/src/main/java/net/discdd/app/k9/K9DDDAdapter.java
password is no longer in the responses, but K9DDDAdapter was not updated.
=> change the K9DDDAdapter to remove password from responses

AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/BundleClientService.java, AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/DDDWifi.java, AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/wifiDirect/DDDWifiDirect.java, bundle-core/src/main/java/net/discdd/pathutils/ClientPaths.java, bundle-core/src/main/java/net/discdd/utils/StoreADUs.java
make sure the client disconnect has really succeeded. fixed small UI and state bugs related to resolving the disconnect problem.
=> DDDWifi client improvements for reliability

AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/BundleClientService.java, bundle-core/src/main/java/net/discdd/client/bundletransmission/BundleTransmission.java
when a recency blob error occurs, manifest it on the UI.
=> improved UI recency error message

AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/BundleTransportService.java, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/screens/AppShareScreen.kt, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/screens/WifiDirectScreen.kt, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/utils/QRCodeGenerator.kt, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/viewmodels/WifiDirectViewModel.kt
adding a WIFI: qr code makes it easy for disconnected clients to connect to the transport for app downloading.
=> add a QR code to connect to wifi direct

AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/BundleClientService.java, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/BundleTransportService.java, AndroidApps/android-core/src/main/java/net/discdd/utils/DDDFixedRateScheduler.java
we weren't setting scheduleFuture to null
this change also moves to utils package rather than util
=> fixed cancel logic for DDDFixedRateScheduler

.idea/codeStyles/Project.xml, AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/BundleClientService.java, AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/wifiDirect/DDDWifiDirect.java, AndroidApps/BundleClient/app/src/main/res/values/strings.xml, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/BundleTransportService.java, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/viewmodels/ServerUploadViewModel.kt, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/wifi/DDDWifiServer.java, AndroidApps/BundleTransport/app/src/main/res/values/strings.xml, AndroidApps/android-core/src/main/java/net/discdd/utils/LogUtil.java, AndroidApps/android-core/src/main/java/net/discdd/utils/UserLogRepository.kt, bundle-core/src/main/java/net/discdd/bundlerouting/service/BundleExchangeServiceImpl.java
this change localizes the strings in the service that will be presented to the user. it also logs the strings to the logger in english.
=> localize strings in the services

AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/BundleClientService.java, AndroidApps/BundleTransport/app/build.gradle, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/BundleTransportService.java, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/screens/AppShareScreen.kt, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/screens/ServerUploadScreen.kt, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/viewmodels/AppShareViewModel.kt, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/viewmodels/ServerUploadViewModel.kt, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/viewmodels/StorageViewModel.kt, AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/viewmodels/WifiDirectViewModel.kt, AndroidApps/BundleTransport/app/src/main/res/values/strings.xml, AndroidApps/android-core/src/main/java/net/discdd/viewmodels/SettingsViewModel.kt, AndroidApps/android-core/src/main/java/net/discdd/viewmodels/WifiBannerViewModel.kt
this code is supposed to help us debug Application-Not-Responding-s
=> ANR debugger
