SJSU-CS-systems-group/DDD

bundleserver/README.md

custom application.properties usage explained in readme, and m2 hack removed from readme

custom application.properties usage explained in readme

---

android-core/src/main/java/net/discdd/android/fragments/LogFragment.java

if we construct logHandler right when we need it,
we avoid race conditions.

static invocation ordering problem with logHandler

---

BundleClient/app/src/main/java/net/discdd/bundleclient/BundleClientWifiDirectService.java
BundleTransport/app/src/main/java/net/discdd/bundletransport/RpcServer.java
BundleTransport/app/src/main/java/net/discdd/bundletransport/TransportWifiDirectFragment.java
BundleTransport/app/src/main/java/net/discdd/bundletransport/TransportWifiDirectService.java
android-core/src/main/java/net/discdd/wifidirect/WifiDirectManager.java
bundle-core/src/main/java/net/discdd/client/bundletransmission/BundleTransmission.java

* added retries to get around the race between client connecting and transport's server starting
* bind transport grpc to port rather than address and port
* streamline owner address tracking in wifi direct manager

fix wifi-direct management for transport

---

BundleClient/app/src/main/java/net/discdd/bundleclient/BundleClientWifiDirectService.java
BundleClient/app/src/main/res/values/strings.xml
BundleTransport/app/src/main/java/net/discdd/bundletransport/TransportWifiDirectService.java
android-core/src/main/java/net/discdd/wifidirect/WifiDirectManager.java

since we are using wifidirect from services, we don't have a lifecycle to hook into. so, we need to make sure to explicitly call initialize/shutdown in service onCreate/onDestroy

need to explicitly call wifidirect initialize/shutdown

---

BundleTransport/app/src/main/java/net/discdd/bundletransport/BundleTransportActivity.java
BundleTransport/app/src/main/java/net/discdd/bundletransport/TransportWifiDirectFragment.java
BundleTransport/app/src/main/res/layout/fragment_transport_wifi_direct.xml
BundleTransport/app/src/main/res/values/strings.xml
android-core/src/main/java/net/discdd/android/fragments/PermissionsFragment.java
android-core/src/main/java/net/discdd/wifidirect/WifiDirectManager.java

move the TransportWifiDirectService binding to the BundleTransportActivity so that we can refresh device info when the BundleTransportActivity sees the permissions change.

update transport wifi direct status when perms change

---

bundleserver/src/main/resources/application.yml

8080 is often a proxy port and when exposed to the internet invites probes. 7778 is one different from the normal transport port.

change the server port to 7778

---

BundleTransport/app/src/main/java/net/discdd/bundletransport/StorageFragment.java

I assumed the recency blob was 120 MB when it really is 145 bytes.

Corrects minimum storage preference

---

BundleClient/app/src/main/AndroidManifest.xml
BundleClient/app/src/main/java/net/discdd/bundleclient/BundleClientWifiDirectService.java
BundleTransport/app/src/main/AndroidManifest.xml
BundleTransport/app/src/main/java/net/discdd/bundletransport/TransportWifiDirectService.java

A notification should pop up on both the client's and transport's phone after the client clicks on "exchanging data" if there is new data to be exchanged. It will disappear after the exchange is complete.
However, the user can manually dismiss the notification before the exchange is completed

Implemented notification on both client and transport

---

bundle-core/src/main/java/net/discdd/client/bundlerouting/ClientRouting.java

Don't allow the value of senderId to be null. The value is null whenever we can't process the recency blob.

Validate sender

---

BundleClient/app/src/main/java/net/discdd/bundleclient/BundleClientActivity.kt
BundleClient/app/src/main/java/net/discdd/bundleclient/screens/ClientUsbScreen.kt
BundleClient/app/src/main/java/net/discdd/bundleclient/screens/HomeScreen.kt
BundleClient/app/src/main/java/net/discdd/bundleclient/screens/WifiDirectScreen.kt
BundleClient/app/src/main/java/net/discdd/bundleclient/viewmodels/UsbViewModel.kt
BundleClient/app/src/main/res/values/strings.xml
android-core/src/main/java/net/discdd/UsbConnectionManager.kt
android-core/src/main/java/net/discdd/screens/NotificationBottomSheet.kt
android-core/src/main/java/net/discdd/screens/PermissionScreen.kt
android-core/src/main/java/net/discdd/viewmodels/SettingsViewModel.kt
android-core/src/main/res/values/strings.xml

- In this pr, I move the `UsbConnectionManger` to `/android-core` so that I can use it for the Transport's version of the USB functionality. 
- I also create a central `SettingsViewModel` for the notifications bottom sheet because it needs to be used on both transport and client.
- I also fix a small error in counting how many times a user denies the permission before bringing them to settings. I also did some minor renaming.

move modular components to android-core

---

BundleClient/app/src/main/java/net/discdd/bundleclient/screens/ServerScreen.kt
BundleClient/app/src/main/java/net/discdd/bundleclient/viewmodels/ServerViewModel.kt

the messages showing the progress of the server exchange is important for the UX. the messages text box is no longer hidden by the easter egg. messages append to the results rather than replace.

append server exchange results in BundleClient

---

bundle-core/src/main/java/net/discdd/bundlerouting/service/BundleExchangeServiceImpl.java

either onError or onComplete should be called for an response observer. not both.

fix onComplete called after onError in BundleExchangeServiceImpl

---

bundle-core/src/main/java/net/discdd/utils/StoreADUs.java

when enumerating ADU files, don't include the metadata files

getAllAppIdAndData in StoreADUs must skip metadata

---

BundleClient/app/src/main/java/net/discdd/bundleclient/BundleClientWifiDirectService.java

We assume the tasks submitted are executed in sequence, so we need a single threaded executor.

Use a single threaded executor in BundleClient

---

BundleClient/app/src/main/java/net/discdd/bundleclient/viewmodels/WifiDirectViewModel.kt

broadcast receivers should only be registered and unregistered on PAUSE an RESUME to make sure it's only registered once.

BundleClient registers broadcast receiver once

---

BundleClient/app/src/main/java/net/discdd/bundleclient/screens/WifiDirectScreen.kt
BundleClient/app/src/main/java/net/discdd/bundleclient/viewmodels/WifiDirectViewModel.kt

Tracking discovery active with a boolean rather than a string allows clearer logic to check active discovery.

track discovery active with a boolean in BundleClient

---

BundleTransport/app/src/main/java/net/discdd/bundletransport/screens/ServerUploadScreen.kt
BundleTransport/app/src/main/java/net/discdd/bundletransport/viewmodels/ServerUploadViewModel.kt

the bundle transport id is long, so display a substring on the UI. this will allow us to diagnose transport issues if they come up.

display a substring of the bundle transport id

---

BundleTransport/app/build.gradle
BundleTransport/app/src/main/java/net/discdd/bundletransport/FileHttpServer.java
BundleTransport/app/src/main/java/net/discdd/bundletransport/TransportWifiDirectService.java
BundleTransport/app/src/main/java/net/discdd/bundletransport/screens/AppShareScreen.kt
BundleTransport/app/src/main/java/net/discdd/bundletransport/screens/TransportHomeScreen.kt

since a phone in a disconnected area cannot install the APKs from the internet, we need a way for disconnected users to install the client and mail apps from the transport.
* embeds a simple http server into the background service.
* the UI displays a QR code for easy download of APKs.
* the UI also allows the transport owner to download the latest APKs from the internet.

enable disconnected client app install from transport

---

BundleClient/app/src/main/AndroidManifest.xml
BundleClient/app/src/main/java/net/discdd/datastore/providers/MessageProvider.java

the custom message provider causes a problem if an app is installed before BundleClient. this removes the custom permissions and checks the calling apps id instead.

open permissions on MessageProvider

---

BundleClient/app/src/androidTest/java/net/discdd/bundleclient/MessageProviderTest.java
BundleClient/app/src/main/java/net/discdd/bundleclient/BundleClientWifiDirectService.java
BundleClient/app/src/main/java/net/discdd/bundleclient/viewmodels/BundleManagerViewModel.kt
BundleClient/app/src/main/java/net/discdd/datastore/providers/MessageProvider.java
bundle-core/src/main/java/net/discdd/client/applicationdatamanager/ApplicationDataManager.java
bundle-core/src/main/java/net/discdd/client/bundlesecurity/ClientSecurity.java
bundle-core/src/main/java/net/discdd/utils/BundleUtils.java
bundle-core/src/main/java/net/discdd/utils/DDDJarFileCreator.java
client-adapter/build.gradle
client-adapter/src/main/AndroidManifest.xml
client-adapter/src/main/java/net/discdd/adapter/DDDClientAdapter.java

* cleans up DDDClient
- explicitly expose reg/unreg methods instead of trying to hook into lifecycle
- only notify when a new ADU comes in

new ADU notifications through DDDClientAdapter 0.2.0

---

apps/k9/common/src/main/java/net/discdd/app/k9/common/ControlAdu.java
apps/k9/common/src/test/java/net/discdd/app/k9/common/ControlAduTest.java

it appears that when classes are minimized, it affects the methods that are available, so we cannot reliably check method names in release builds.

remove properties check from ControlAdu

---

AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/BundleTransportService.java
AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/screens/TransportHomeScreen.kt
AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/service/DDDWifiServiceEvents.kt
AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/viewmodels/WifiDirectViewModel.kt
AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/wifi/DDDWifiServer.java

on first startup, the transport background service doesn't have permissions to do wifi direct.
once those permissions are obtained, we notify the background service so that it can retry.

reinitialize wifi direct if permissions were missing

---

AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/BundleClientService.java

when scheduling the background transmissions, set the initial delay to the normal delay. with no initial delay, the background transmissions race initialization.

delayed start to background transmissions

---

AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/BundleClientService.java
AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/BundleTransportService.java

the activities may try to repeatedly start the background service, but it should only be started once.

make sure background service is only started once

---

AndroidApps/BundleClient/app/src/main/java/net/discdd/bundleclient/service/wifiDirect/DDDWifiDirect.java
AndroidApps/BundleTransport/app/src/main/java/net/discdd/bundletransport/wifi/DDDWifiServer.java

we don't need the location permission on android 33+ which is what we are targetting.

only require NEARBY_WIFI_DEVICES permission to enable wifip2p
